version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "3333:3333"
    expose:
      - "3333"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - PORT=3333
      - MONGOOSE_CONNECTION_STRING=mongodb://mongo:27017/db
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    logging:
      driver: none
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
